const stockProductos = [
    { id: 1, categoria: "lacteos", marca: "Leche gloria entera lata 395g", imagen: "https://lh3.googleusercontent.com/pw/AP1GczOd6WRbDl-OP-bJGVMxHdywQ76jAGKEL7jFo_-demmaH_t9MSkuJqW1SYROg_PhfPeWRAfP2cIwS6kqlj0uE3kGsJ9jSWJ7XIbWWj8PGp5mYmYESIqNFt3YnLCBbebcQPC-hMVOBjICNNTYq3nlMQbc=w360-h360-s-no-gm?authuser=0", precio: 4.2, disponible: "DISPONIBLE", detalles: ["Leche gloria", "reconstituida entera", "Lata 395g"] },
    { id: 2, categoria: "lacteos", marca: "Leche gloria entera  lata 170g", imagen: "https://lh3.googleusercontent.com/pw/AP1GczP8oBza3x4h4M86NW3Ku0g-NVhq8T09s1e4sOqYRtHDyoatBOWy033KOsezW5AEQOR_7dTvno-2wrUU75TJtR6EPljdSMH0TqEm8BIelRZKRrM2MiU", precio: 2.2, disponible: "DISPONIBLE", detalles: ["Leche GLORIA", "Entera Reconstituida", "Lata 170g"] },
    { id: 3, categoria: "bebidas", marca: "Yogurt gloria  Lúcuma botella 180g", imagen: "https://lh3.googleusercontent.com/pw/AP1GczNMngnYzgAKiTixWl1t8fgeBVBp0bjCMckvVucQVBMimb1FdsOU0u7MaJmrqn1TZQzXGGg5MlfEDCY9_wJyOeUjTHaFIxKlFiP6imI1-mwOsdl2Cgc", precio: 1.9, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Lúcuma", "botella 180g"] },
    { id: 4, categoria: "bebidas", marca: "Yogurt gloria  Durazno botella 180g", imagen: "https://lh3.googleusercontent.com/pw/AP1GczMl6bqrBY4ceOwm0yeYIOWvXxkTgx5dyWMIjrkilg5YYkqnOQvsgZmAsfS0_KmTXFw0i4Yo0gRdcIonBJf2d5YnO6gLJPsoqFBDsk3HzLNmUzcBu40", precio: 1.9, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Durazno", "botella 180g"] },
    { id: 5, categoria: "bebidas", marca: "Yogurt gloria  fresa botella 180g", imagen: "https://lh3.googleusercontent.com/pw/AP1GczP7JGi23TGiClSk2bx88pnIRupbc_iMWAW-X2Xdjy4Ay0G1bvqNX93tWiCxOb8zTgZtw3gerCkFNYq6baIP-lLzqNotnoYPi-UGtr9j6b0RksOkeec", precio: 1.9, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Fresa", "botella 180g"] },
    { id: 6, categoria: "bebidas", marca: "Yogurt gloria  vainilla botella 180g", imagen: "https://lh3.googleusercontent.com/pw/AP1GczN7MPk0wYN0MVpDpVhWFXHthzOTooiJIh7nrUeWx7eK0Ad_GjHP3QWZx7-3g-6cRKkI7KNCIMnTNXPjOe-_B1leYHAH52YkwdBGPDoF7YWzPmxoHMU", precio: 1.9, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Vainilla", "botella 180g"] },
    { id: 7, categoria: "bebidas", marca: "Yogurt gloria  Fresa y plátano botella 180g", imagen: "https://lh3.googleusercontent.com/pw/AP1GczMLK_48GrgpNNUV6yWalYb3t-9_DXXM_NnlzXeuyOc44iQM2RjzbtmYNW6kXfJwTTswAmslVkTqocApu0g8ayLL_kCVEEvt1adOnnVksPgFTd4Mwbk", precio: 1.9, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Fresa y Plátano", "botella 180g"] },
    { id: 8, categoria: "lacteos", marca: "Leche condensada gloria lata 393g", imagen: "https://lh3.googleusercontent.com/pw/AP1GczO__DX4sug3JNOLccdOHnKe9QPueGKspbqOjHBO16yiWX2BbXB99lCaDUk-L4AFdI1nZzJrObkUM01ZgUPEK7qG97f5xegc1U_bqGpx4sM0XhELuQU", precio: 6.3, disponible: "DISPONIBLE", detalles: ["Leche condensada ", "gloria ", "lata 393g"] },
    { id: 9, categoria: "bebidas", marca: "Bebida gloria Mango caja 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczMq468RxZCt-r8Yz-skOV-QduZUUttlM0LiVFhBTpGnb3QoAN7YayaLLRe39mHK6qkQcqUMOcw7H5otYfQRXydAm8dTDbISMSts1eJr91b9nfGawhw", precio: 4.5, disponible: "DISPONIBLE", detalles: ["Bebida ", "gloria", "sabor Mango ", "caja 1L"] },
    { id: 10, categoria: "bebidas", marca: "Bebida gloria Durazno caja 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczMq468RxZCt-r8Yz-skOV-QduZUUttlM0LiVFhBTpGnb3QoAN7YayaLLRe39mHK6qkQcqUMOcw7H5otYfQRXydAm8dTDbISMSts1eJr91b9nfGawhw", precio: 4.5, disponible: "DISPONIBLE", detalles: ["Bebida ", "gloria", "sabor Durazno", "caja 1L"] },
    { id: 11, categoria: "bebidas", marca: "Bebida gloria Naranja caja 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczNNzN-wASCbduDHk-jC1Wir4rvuCbgvA21oVSIyhLuE6H5l8yDBbLmSUJFph6Gy3y14z-FKpYvEqS1A1aYHWN-HVr66nAo--efjTfoLJikSHeLjms4", precio: 4.5, disponible: "DISPONIBLE", detalles: ["Bebida ", "gloria", "sabor Naranja", "caja 1L"] },
    { id: 12, categoria: "bebidas", marca: "Bebida gloria Maracuyá caja 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczMq468RxZCt-r8Yz-skOV-QduZUUttlM0LiVFhBTpGnb3QoAN7YayaLLRe39mHK6qkQcqUMOcw7H5otYfQRXydAm8dTDbISMSts1eJr91b9nfGawhw", precio: 4.5, disponible: "DISPONIBLE", detalles: ["Bebida ", "gloria", "sabor Maracuyá", "caja 1L"] },
    { id: 13, categoria: "bebidas", marca: "Bebida gloria Piña caja 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczMq468RxZCt-r8Yz-skOV-QduZUUttlM0LiVFhBTpGnb3QoAN7YayaLLRe39mHK6qkQcqUMOcw7H5otYfQRXydAm8dTDbISMSts1eJr91b9nfGawhw", precio: 4.5, disponible: "DISPONIBLE", detalles: ["Bebida ", "gloria", "sabor Piña", "caja 1L"] },
    { id: 14, categoria: "bebidas", marca: "Yogurt gloria  fresa botella 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczOf3V-5pg8QRIEqvxevqiha8IbUcH_aChecBuYb6DqLYHX4tTxVKLphaZCO9E6hAW-iuBfmylgntaCw7Bpn0mluLlZ03x1Cijl0pc7EipQqciHW840=w2400", precio: 5.7, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Fresa", "botella 1L"] },
    { id: 15, categoria: "bebidas", marca: "Yogurt gloria  Vainilla botella 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczO_UgghmWTZ4fwGmSmGycoFBpr_6xQ9WnNYItOpzwQhEDtG1E6VLKqe9aIAZrR9EPMSVVsdi5o_9T1O7h5DWDTIjeTFiZkDj_2JUcq9tFr-WxT71YQ", precio: 5.7, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Vainilla", "botella 1L"] },
    { id: 16, categoria: "bebidas", marca: "Yogurt gloria  Lúcuma botella 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczPO9XLPt2FhaD6oZDeb-S6gg5Mm-NUSb04siYAdnj-DL1Gd9IGh1nZRSvjZk8N9R_GnVzD1iBKp9LxUVRTKntNRg3wGvENLUyBFi35J7yontGyhrlI", precio: 5.7, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Lúcuma", "botella 1L"] },
    { id: 17, categoria: "bebidas", marca: "Yogurt gloria  Durazno botella 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczPj0ouHh1LzXR5oa4XLUVbab-y5MCK3HwUGS7aQERJYvGf3iEplNPwZlXWZLohk1cP0YGboNasi7WBXdH_iucKzR0l44jJaDyqm0iZv4XEmWKqGP7k", precio: 5.7, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Durazno", "botella 1L"] },
    { id: 18, categoria: "bebidas", marca: "Yogurt gloria  Tutti frutti botella 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczOMReKgbH7qPPHEfTN8SSBbuYuxzcyfEONw9Dj2Ruk6Ly20b5GtmIrDLAGJ-EjKJ7EY85a2yTdw-eNsXwDVLMOw3-SostRWHG6GdAg2Kqy-jfDwUxY", precio: 5.7, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Tutti frutti", "botella 1L"] },
    { id: 19, categoria: "bebidas", marca: "Yogurt gloria  Guanábana botella 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczMVLwnlSQvZZ6dO0_bQKxiRCIhed3-mbDX3S_T7FNZz51Yx9W60GnWqBsYP1i_o3CS9zf1q8GeqjQBlhCpJF3hyo02bbrcims70oeXKGIYElGtWg-g", precio: 5.7, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Guanábana", "botella 1L"] },
    { id: 20, categoria: "bebidas", marca: "Yogurt gloria  Natural botella 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczP9u6OGxsJKaJUewgUxt48o1dp0aBlVPGf6BdiEYF_8Y-W6Ub9ZMfXMtVt3gG62k_6HXchRaZ491R3KKsATH2D5rT43Tujx2IMz-q_lwEo5a2fcC1g", precio: 5.7, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Natural", "botella 1L"] },
    { id: 21, categoria: "bebidas", marca: "Yogurt gloria  Fresa y plátano botella 1L", imagen: "https://lh3.googleusercontent.com/pw/AP1GczP9u6OGxsJKaJUewgUxt48o1dp0aBlVPGf6BdiEYF_8Y-W6Ub9ZMfXMtVt3gG62k_6HXchRaZ491R3KKsATH2D5rT43Tujx2IMz-q_lwEo5a2fcC1g", precio: 5.7, disponible: "DISPONIBLE", detalles: ["Yogurt bebible ", "gloria ", "sabor Fresa y Plátano", "botella 1L"] }
];
// Feha de modificacion:23/9/2024 04:55:06